### ISSUE TITLE
in day 2 you need to add output of images

### ISSUE THREAD

**Issue by ombharamadev** [iguptashivam/CEI-Virtual-Internship#3]
in day 2 you need to add output of images
![image](https://github.com/iguptashivam/CEI-Virtual-Internship/assets/150242178/4bbe1557-3789-40ee-a938-c31e197cee28)

**Comment by iguptashivam** [comment]
updated

**Comment by ombharamadev** [comment]
ok

**Comment by iguptashivam** [comment]
Already added
https://github.com/iguptashivam/CEI-Virtual-Internship/tree/main/Day-2%20Assingment
